# Generated by Django 5.0.6 on 2024-06-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('walk', models.BooleanField(default=False)),
                ('coffee', models.BooleanField(default=False)),
                ('tea', models.BooleanField(default=False)),
            ],
        ),
    ]
